import type { Metadata } from "next";
import Image from "next/image";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "Pool Table Services", description: "Moving, recovering, repair, leveling, rail and cushion work from The Pool Table Store in Alexandria, VA.", alternates: { canonical: "/services" }, robots: { index: false, follow: false } };

export default function ServicesPage() { return <><Header/><main>
  <section className="page-hero"><div className="wrap page-hero-grid"><div><div className="eyebrow">Service & precision</div><h1 className="section-title">The details are the difference.</h1></div><div><p>Pool tables are precision instruments. We handle the work that keeps the geometry, response, and finish in balance.</p><div className="route-links"><a className="button" href="tel:+15712362119">Call for an assessment</a><a className="button secondary" href="#service-list">See service scope</a></div></div></div></section>
  <section className="section" id="service-list"><div className="wrap"><div className="eyebrow">The full service bench</div><div className="service-detail-grid"><article className="service-detail"><span className="num">01 / MOVE</span><h3>Move & relocate</h3><p>Disassembly, padding, safe transport, exacting reassembly, and leveling for a table that needs a new address.</p></article><article className="service-detail"><span className="num">02 / RECOVER</span><h3>Recover & re-felt</h3><p>Cloth replacement with careful nap direction, tension, seam work, and a clean finished surface.</p></article><article className="service-detail"><span className="num">03 / REPAIR</span><h3>Repair & level</h3><p>Slate leveling, rail alignment, cushion replacement, pocket work, frame repairs, and minor surface fixes.</p></article></div></div></section>
  <section className="section light-panel"><div className="wrap editorial-split"><div className="route-image"><Image src="/assets/repair-rail.jpeg" alt="Pool table rail and cushion repair" fill sizes="(max-width: 800px) 100vw, 55vw"/><span className="route-image-caption">Repair / rail detail</span></div><div><div className="eyebrow">Before work begins</div><h2 className="section-title">A clear estimate, then careful execution.</h2><div className="editorial-copy"><p>Call or text with the table size, photos, and a description of the issue. For more involved projects, we arrange an on-site inspection and provide a written estimate before work begins.</p></div><div className="catalog-list"><div className="catalog-row"><span className="num">01</span><h3>Assess</h3><p>We look at slate, rails, cushions, pockets, cloth, frame, and access.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">02</span><h3>Protect</h3><p>We plan the path and protect your home during disassembly and transport.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">03</span><h3>Calibrate</h3><p>We verify level, alignment, pocket placement, and cloth tension at the finish.</p><span className="arrow">↗</span></div></div></div></div></section>
  <section className="section process"><div className="wrap intro-grid"><div><div className="eyebrow">Service area</div><h2 className="section-title">Alexandria and the surrounding region.</h2></div><div><p>Primary service zones include Alexandria, Arlington County, Fairfax County, and Mount Vernon. Out-of-area requests are evaluated individually.</p><a className="button" href="tel:+15712362119">Discuss your table</a></div></div></section>
 </main><Footer/></>; }
