import type { Metadata } from "next";
import Image from "next/image";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "Contact The Pool Table Store", description: "Call or text The Pool Table Store in Alexandria, Virginia for a consultation, estimate, sales question, or service appointment.", alternates: { canonical: "/contact" }, robots: { index: false, follow: false } };

export default function ContactPage() { return <><Header/><main>
  <section className="page-hero"><div className="wrap page-hero-grid"><div><div className="eyebrow">Start here</div><h1 className="section-title">Tell us about the table.</h1></div><div><p>For the fastest response, call or text. We’ll help you understand the next step without a generic form or a handoff.</p><a className="button" href="tel:+15712362119">Call or text (571) 236-2119</a></div></div></section>
  <section className="section"><div className="wrap contact-rail"><div><h3>Call or text</h3><p>Primary line for sales questions, moving and repair estimates, restoration conversations, and appointment coordination.</p><p className="quote-band"><a href="tel:+15712362119">(571) 236-2119</a></p></div><div><h3>Visit the showroom</h3><p>7819 Colonial Springs Blvd<br/>Alexandria, VA 22306</p><p className="quote-band">Every day<br/>8:00 AM–8:00 PM</p></div></div></section>
  <section className="section light-panel"><div className="wrap editorial-split"><div><div className="eyebrow">What to bring to the call</div><h2 className="section-title">A few details make the first answer better.</h2></div><div><div className="catalog-list"><div className="catalog-row"><span className="num">01</span><h3>Table details</h3><p>Type and size, if known, plus anything you know about the table’s history.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">02</span><h3>Photos</h3><p>For repair and restoration, photos or a short video can help with a preliminary assessment.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">03</span><h3>Room & access</h3><p>For a move or installation, note room dimensions, doorways, stairs, and the preferred date range.</p><span className="arrow">↗</span></div></div><a className="button" href="tel:+15712362119">Call the showroom</a></div></div></section>
  <section className="section"><div className="wrap editorial-split reverse"><div className="route-image small"><Image src="/assets/official-graphic.png" alt="Pool balls and cues on a blue billiards table" fill sizes="(max-width: 800px) 100vw, 55vw"/><span className="route-image-caption">Alexandria / Virginia</span></div><div><div className="eyebrow">Service area</div><h2 className="section-title">Alexandria first.<br/>The region, too.</h2><div className="editorial-copy"><p>Primary zones include Alexandria, Arlington County, Fairfax County, and Mount Vernon. Out-of-area requests are evaluated individually.</p></div></div></div></section>
 </main><Footer/></>; }
