import type { Metadata } from "next";
import Image from "next/image";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "Pool Tables & Selection", description: "Explore new and used pool tables, accessories, and professional setup from The Pool Table Store in Alexandria, Virginia.", alternates: { canonical: "/tables" }, robots: { index: false, follow: false } };

export default function TablesPage() { return <><Header/><main>
  <section className="page-hero light-panel"><div className="wrap page-hero-grid"><div><div className="eyebrow">Sales & selection</div><h1 className="section-title">The right table changes the room.</h1></div><div><p>Choose with a specialist who understands scale, clearance, finish, and how the table should feel when the room is complete.</p><div className="route-links"><a className="button" href="tel:+15712362119">Call about current tables</a><a className="button secondary" href="#selection">How selection works</a></div></div></div></section>
  <section className="section light-panel" id="selection"><div className="wrap editorial-split"><div><div className="eyebrow">A considered purchase</div><h2 className="section-title">Space first.<br/>Style second.<br/>Play always.</h2></div><div className="editorial-copy"><p>The Pool Table Store offers new and used tables, with guidance to help you find an option that suits your room, your style, and the way you plan to play.</p><p>Call for current selection and a free design consultation. We can talk through room dimensions, clearance, finishes, and delivery logistics before you commit to a table.</p><div className="quote-band">Every new table includes delivery and professional setup.</div></div></div></section>
  <section className="section"><div className="wrap editorial-split reverse"><div className="route-image"><Image src="/assets/table-sale.jpeg" alt="Pool table available for selection" fill sizes="(max-width: 800px) 100vw, 60vw"/><span className="route-image-caption">Selection / setup</span></div><div><div className="eyebrow">What we can help with</div><div className="catalog-list"><div className="catalog-row"><span className="num">01</span><div><h3>Table scale</h3></div><p>Talk through the room, walking clearance, and the footprint that will let the table breathe.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">02</span><div><h3>Finish & character</h3></div><p>Compare wood finishes, rail styles, leg profiles, and the details that make the table yours.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">03</span><div><h3>Room essentials</h3></div><p>Complete the setup with cues, racks, balls, brushes, bridges, books, videos, and lighting.</p><span className="arrow">↗</span></div></div></div></div></section>
  <section className="section services"><div className="wrap intro-grid"><div><div className="eyebrow">Ready to look?</div><h2 className="section-title">Tell us what the room needs.</h2></div><div><p>Bring your room dimensions and design references to the conversation. We’ll help you understand what fits and what is currently available.</p><a className="button" href="tel:+15712362119">Call or text (571) 236-2119</a></div></div></section>
 </main><Footer/></>; }
