import type { Metadata } from "next";
import Image from "next/image";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "About The Pool Table Store", description: "A dedicated Alexandria pool table specialist serving the Washington, DC area since 1990.", alternates: { canonical: "/about" }, robots: { index: false, follow: false } };

export default function AboutPage() { return <><Header/><main>
  <section className="page-hero light-panel"><div className="wrap page-hero-grid"><div><div className="eyebrow">About the specialist</div><h1 className="section-title">Focused expertise.<br/>Straight answers.</h1></div><div><p>The Pool Table Store has served the Washington, DC area from Alexandria since 1990, specializing exclusively in pool tables and related services.</p></div></div></section>
  <section className="section light-panel"><div className="wrap editorial-split reverse"><div className="route-image"><Image src="/assets/table-room.jpeg" alt="Pool table in a finished game room" fill sizes="(max-width: 800px) 100vw, 55vw"/><span className="route-image-caption">A table should belong in the room.</span></div><div><div className="eyebrow">The reason we exist</div><h2 className="section-title">Not furniture movers. Table specialists.</h2><div className="editorial-copy"><p>A pool table is more than a large piece of furniture. Its slate, rails, cushions, cloth, and level define how it plays.</p><p>That is why every service we offer is built around the table itself: sales, delivery, installation, moving, recovery, repair, maintenance, and restoration.</p></div></div></div></section>
  <section className="section"><div className="wrap"><div className="eyebrow">What dedication looks like</div><div className="catalog-list"><div className="catalog-row"><span className="num">01</span><h3>Specialization</h3><p>Over 30 years serving Alexandria and surrounding communities with pool-table-only expertise.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">02</span><h3>Clarity</h3><p>Written estimates, straightforward scope, and a conversation before work begins.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">03</span><h3>Care</h3><p>Protection for your home, careful handling, and a final check for level, alignment, and cloth tension.</p><span className="arrow">↗</span></div></div></div></section>
  <section className="section process"><div className="wrap intro-grid"><div><div className="eyebrow">Come see us</div><h2 className="section-title">7819 Colonial Springs Blvd.</h2></div><div><p>Our Alexandria showroom is the place to discuss a table, a move, a repair, or a restoration.</p><a className="button" href="tel:+15712362119">Call before you visit</a></div></div></section>
 </main><Footer/></>; }
