import Image from "next/image";
import Link from "next/link";
import { Footer, Header } from "./components";

const phone = "tel:+15712362119";

export default function Home() {
  return <><Header/><main id="top">
    <section className="hero"><Image className="hero-photo" src="/assets/table-sale.jpeg" alt="Pool table in a finished room" fill priority sizes="100vw"/><div className="hero-shade"/><div className="wrap hero-content"><p className="eyebrow">Alexandria’s pool table specialist</p><h1 className="display">Pool tables.<br/>Expertly set up.</h1><p className="hero-intro">Choose a table, move one safely, or bring an older table back into play. We handle sales, installation, repair, recovery, and restoration.</p><div className="hero-actions"><a className="button" href={phone}>Call (571) 236-2119</a><a className="button ghost" href="sms:+15712362119">Text for an estimate</a></div><p className="hero-note">Serving Alexandria, Arlington, Fairfax, and Mount Vernon</p></div></section>
    <section className="route-section" aria-labelledby="choose-title"><div className="wrap"><div className="section-kicker"><p className="eyebrow">What brings you in?</p><h2 id="choose-title">Start with the table you have—or the one you want.</h2></div><div className="route-grid"><Link className="route-card" href="/tables"><span>01</span><h3>Buy a table</h3><p>New and pre-owned tables, room guidance, delivery, and professional setup.</p><b>Explore tables →</b></Link><Link className="route-card" href="/services"><span>02</span><h3>Move or repair</h3><p>Disassembly, transport, recovery, rails, cushions, pockets, repair, and leveling.</p><b>View services →</b></Link><Link className="route-card" href="/restoration"><span>03</span><h3>Restore a table</h3><p>A measured approach for antique and sentimental tables that deserve another chapter.</p><b>See restoration →</b></Link></div></div></section>
    <section className="section proof-section"><div className="wrap proof-grid"><div className="proof-copy"><p className="eyebrow">Specialized work</p><h2 className="section-title">A pool table is a precision instrument.</h2><p>Slate, rails, cushions, cloth, pockets, and level work together. We focus on that complete system so the table looks right, plays right, and stays that way.</p><ul className="check-list"><li>Pool-table-only expertise since 1990</li><li>Written estimates before work begins</li><li>Sales, service, and restoration in one place</li></ul><a className="text-link" href="/about">Why specialization matters →</a></div><figure className="feature-image"><Image src="/assets/repair-rail.jpeg" alt="Close view of a pool table rail and playing surface" fill sizes="(max-width: 800px) 100vw, 52vw"/><figcaption>Rail, cushion, cloth, and playing-surface detail</figcaption></figure></div></section>
    <section className="section showroom-band"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Sales and setup</p><h2 className="section-title">Plan the room before choosing the table.</h2></div><p>Start with room dimensions, cue clearance, access, and how you want the room to feel. We can help narrow the size and setup before you commit.</p></div><div className="room-steps"><div><span>Measure</span><strong>Room length and width</strong><p>Bring exact dimensions, including any tight corners or fixed furniture.</p></div><div><span>Check</span><strong>Playing clearance</strong><p>Allow space around every side for a comfortable cue stroke. We’ll help assess the room.</p></div><div><span>Plan</span><strong>Delivery access</strong><p>Note stairs, doorways, turns, and the path into the final room.</p></div></div><Link className="button light-button" href="/tables">Plan your table</Link></div></section>
    <section className="section image-story"><div className="wrap image-story-grid"><figure><Image src="/assets/antique-restoration.jpeg" alt="Antique pool table with carved woodwork" fill loading="eager" sizes="(max-width: 800px) 100vw, 58vw"/></figure><div><p className="eyebrow">Restoration</p><h2 className="section-title">Keep the character. Restore the play.</h2><p>We assess the structure, slate, rails, pockets, cloth, and finish before recommending a path forward for an older or sentimental table.</p><Link className="button" href="/restoration">Explore restoration</Link></div></div></section>
    <section className="section process"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">How service works</p><h2 className="section-title">Clear before, careful during, checked at the end.</h2></div><p>Send the basics first. We’ll help determine the scope and the next useful step.</p></div><ol className="process-list"><li><span>01</span><div><h3>Tell us about the table</h3><p>Share the size, photos, room details, access, and what you want to accomplish.</p></div></li><li><span>02</span><div><h3>Review the scope</h3><p>We assess the table and provide a written estimate before work begins.</p></div></li><li><span>03</span><div><h3>Complete the work</h3><p>We protect the home, handle the table properly, and set it up with care.</p></div></li><li><span>04</span><div><h3>Verify the result</h3><p>Level, alignment, cushion response, and cloth tension are checked at the finish.</p></div></li></ol></div></section>
    <section className="contact-band"><div className="wrap contact-band-grid"><div><p className="eyebrow">Ready to start?</p><h2>Tell us about the table.</h2><p>Call for a conversation or text a few details and photos.</p></div><div className="contact-actions"><a className="button light-button" href={phone}>Call (571) 236-2119</a><a className="button outline-light" href="sms:+15712362119">Text the showroom</a><span>Every day · 8:00 AM–8:00 PM</span></div></div></section>
  </main><Footer/></>;
}
