import Image from "next/image";
import { Header } from "./components";

const phone = "tel:+15712362119";

export default function Home() {
  return <main id="top"><Header/>
    <section className="hero"><div className="wrap hero-content"><div className="eyebrow">Pool table sales · service · restoration</div><h1 className="display">Keep the<br/><em>table true.</em></h1><p className="hero-intro">The Pool Table Store brings decades of specialized knowledge to every move, repair, recovery, and new-table installation in Alexandria and the surrounding region.</p><div className="hero-actions"><a className="button" href={phone}>Call or text for an estimate</a><a className="button secondary" href="#services">Explore services</a></div></div><div className="hero-index">Alexandria, Virginia / 01</div></section>
    <section className="section"><div className="wrap intro-grid"><div><div className="eyebrow">A dedicated specialist</div><h2 className="section-title">A better playing experience starts underneath.</h2></div><div><p>A pool table is a precision instrument. Slate, rails, cloth, and level all have to work together. We focus exclusively on that relationship, so your table looks right, plays right, and stays that way.</p><div className="number-list"><div className="number-row"><span className="num">01</span><strong>30+ years of specialization</strong><span>↗</span></div><div className="number-row"><span className="num">02</span><strong>Sales, service & restoration</strong><span>↗</span></div><div className="number-row"><span className="num">03</span><strong>Alexandria-based, regional reach</strong><span>↗</span></div></div></div></div></section>
    <section className="section services" id="services"><div className="wrap"><div className="service-head"><div><div className="eyebrow">What we do</div><h2 className="section-title">One specialist.<br/>Every table need.</h2></div><p>From the first room measurement to the final level check, our work is built around accuracy, care, and clear communication.</p></div><div className="service-grid"><article className="service feature"><span className="num">01 / SALES</span><h3>Find the right table.</h3><p>New and pre-owned tables, custom finishes, room guidance, delivery, and professional installation.</p></article><article className="service"><span className="num">02 / MOVING</span><h3>Move it without compromise.</h3><p>Careful disassembly, padded transport, precise reassembly, and leveling for local relocations.</p></article><article className="service"><span className="num">03 / REPAIR</span><h3>Bring the play back.</h3><p>Slate leveling, cushion and rail replacement, pocket repair, frame work, and cloth recovery.</p></article><article className="service"><span className="num">04 / RESTORATION</span><h3>Preserve its character.</h3><p>Antique and sentimental table restoration that balances original character with reliable playability.</p></article></div></div></section>
    <section className="section"><div className="wrap showcase"><figure className="image-block tall"><Image src="/assets/antique-restoration.jpeg" alt="Antique pool table restoration detail" fill sizes="(max-width: 800px) 100vw, 50vw"/><figcaption className="image-caption"><span>Restoration</span><strong>Old tables.<br/>New life.</strong></figcaption></figure><div className="showcase"><figure className="image-block"><Image src="/assets/repair-rail.jpeg" alt="Pool table rail and cushion repair" fill sizes="(max-width: 800px) 100vw, 50vw"/><figcaption className="image-caption"><span>Repair</span><strong>Precision<br/>in the details.</strong></figcaption></figure><figure className="image-block"><Image src="/assets/table-sale.jpeg" alt="Pool table ready for sale" fill sizes="(max-width: 800px) 100vw, 50vw"/><figcaption className="image-caption"><span>Sales</span><strong>Make room<br/>for a classic.</strong></figcaption></figure></div></div></section>
    <section className="section process" id="process"><div className="wrap process-grid"><div><div className="eyebrow">The way we work</div><h2 className="section-title">Good work is measured twice.</h2></div><div className="process-list"><div className="process-item"><span className="num">01</span><div><h3>Talk it through</h3><p>Call or text with your table size, photos, room dimensions, and what you want to accomplish.</p></div></div><div className="process-item"><span className="num">02</span><div><h3>Assess the work</h3><p>We diagnose the table and its surroundings, then provide a clear written estimate before work begins.</p></div></div><div className="process-item"><span className="num">03</span><div><h3>Do it precisely</h3><p>Our team protects your home, handles the table properly, and follows through with professional setup.</p></div></div><div className="process-item"><span className="num">04</span><div><h3>Check the result</h3><p>We verify level, alignment, cushion response, and cloth tension before we call it finished.</p></div></div></div></div></section>
    <section className="section areas"><div className="wrap areas-grid"><div><div className="eyebrow">Where we work</div><h2 className="section-title">Alexandria first.<br/>The region, too.</h2><p>Our primary service area includes Alexandria, Arlington County, Fairfax County, and Mount Vernon. For out-of-area requests, call to discuss timing and travel.</p><a className="button" href={phone}>Discuss your project</a></div><div className="area-stamp"><span>Alexandria<br/>Arlington<br/>Fairfax<br/>Mount Vernon</span></div></div></section>
    <section className="section contact" id="contact"><div className="wrap contact-grid"><div><div className="eyebrow">Start a conversation</div><h2 className="section-title">Tell us about the table.</h2><p className="hero-intro">Call or text for a consultation, service question, sales appointment, or written estimate. We’ll help you understand the next right step.</p><a className="button" href={phone}>Call or text (571) 236-2119</a></div><div className="contact-details"><div className="detail"><label>Phone / text</label><a href={phone}>(571) 236-2119</a></div><div className="detail"><label>Showroom</label><span>7819 Colonial Springs Blvd<br/>Alexandria, VA 22306</span></div><div className="detail"><label>Hours</label><span>Every day, 8:00 AM–8:00 PM</span></div><div className="detail"><label>Service areas</label><span>Alexandria · Arlington<br/>Fairfax · Mount Vernon</span></div></div></div></section>
    <footer className="footer"><div className="wrap"><span>© {new Date().getFullYear()} The Pool Table Store</span><span>Demo site · <a href="https://syncedupsolutions.com" rel="noreferrer">Powered by SyncedUp</a></span></div></footer>
  </main>;
}
