import type { Metadata } from "next";
import Image from "next/image";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "Pool Table Restoration", description: "Thoughtful antique and sentimental pool table restoration in Alexandria, Virginia.", alternates: { canonical: "/restoration" }, robots: { index: false, follow: false } };

export default function RestorationPage() { return <><Header/><main>
  <section className="page-hero"><div className="wrap page-hero-grid"><div><div className="eyebrow">Antique & sentimental tables</div><h1 className="section-title">Preserve the character. Restore the play.</h1></div><div><p>Restoration is a balance: structural and functional improvements without sanding away what makes the table worth keeping.</p><div className="route-links"><a className="button" href="tel:+15712362119">Call about restoration</a><a className="button secondary" href="sms:+15712362119">Text photos of the table</a></div></div></div></section>
  <section className="section"><div className="wrap editorial-split"><div><div className="eyebrow">A measured approach</div><h2 className="section-title">The finish matters.<br/>So does what is underneath.</h2><div className="editorial-copy"><p>We assess the frame, legs, slate, rails, pockets, cloth, and original finish before recommending a path forward.</p><p>Where appropriate, techniques are reversible or minimally invasive, keeping the table’s identity intact while returning it to reliable play.</p></div></div><div className="route-image"><Image src="/assets/antique-restoration.jpeg" alt="Antique pool table restoration" fill sizes="(max-width: 800px) 100vw, 55vw"/><span className="route-image-caption">Restoration / original character</span></div></div></section>
  <section className="section light-panel"><div className="wrap editorial-split reverse"><div className="route-image small"><Image src="/assets/restoration-detail.jpeg" alt="Close-up detail from a pool table restoration" fill sizes="(max-width: 800px) 100vw, 55vw"/><span className="route-image-caption">Detail / material care</span></div><div><div className="eyebrow">The restoration sequence</div><div className="catalog-list"><div className="catalog-row"><span className="num">01</span><h3>Document</h3><p>Photograph and understand the table as it is, including its original finishes and wear.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">02</span><h3>Stabilize</h3><p>Address frame, leg, slate, and structural concerns before surface work begins.</p><span className="arrow">↗</span></div><div className="catalog-row"><span className="num">03</span><h3>Restore</h3><p>Refinish, repair, recover, and set up with a clear eye toward character and playability.</p><span className="arrow">↗</span></div></div></div></div></section>
  <section className="section"><div className="wrap intro-grid"><div><div className="eyebrow">Have a family table?</div><h2 className="section-title">Start with photographs.</h2></div><div><p>Share a few photos, table dimensions if known, and the story of the piece. We’ll help you understand whether restoration is the right next step.</p><div className="route-links"><a className="button" href="tel:+15712362119">Call about the table</a><a className="button secondary" href="sms:+15712362119">Text photos</a></div></div></div></section>
 </main><Footer/></>; }
